name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: |
          npm install
          npx cypress install  # Adiciona o passo para garantir que o binário do Cypress seja instalado

      - name: Clean up old videos and screenshots
        run: |
          rm -rf cypress/videos
          rm -rf cypress/screenshots

      - name: Run Cypress tests
        run: npx cypress run